/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModulesUsersWebRouteImport } from './routes/modules.users-web'
import { Route as ModulesUsersMobileRouteImport } from './routes/modules.users-mobile'
import { Route as ModulesPostsRouteImport } from './routes/modules.posts'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesUsersWebRoute = ModulesUsersWebRouteImport.update({
  id: '/modules/users-web',
  path: '/modules/users-web',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesUsersMobileRoute = ModulesUsersMobileRouteImport.update({
  id: '/modules/users-mobile',
  path: '/modules/users-mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesPostsRoute = ModulesPostsRouteImport.update({
  id: '/modules/posts',
  path: '/modules/posts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/modules/posts': typeof ModulesPostsRoute
  '/modules/users-mobile': typeof ModulesUsersMobileRoute
  '/modules/users-web': typeof ModulesUsersWebRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/modules/posts': typeof ModulesPostsRoute
  '/modules/users-mobile': typeof ModulesUsersMobileRoute
  '/modules/users-web': typeof ModulesUsersWebRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/modules/posts': typeof ModulesPostsRoute
  '/modules/users-mobile': typeof ModulesUsersMobileRoute
  '/modules/users-web': typeof ModulesUsersWebRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/modules/posts'
    | '/modules/users-mobile'
    | '/modules/users-web'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/modules/posts'
    | '/modules/users-mobile'
    | '/modules/users-web'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/modules/posts'
    | '/modules/users-mobile'
    | '/modules/users-web'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ModulesPostsRoute: typeof ModulesPostsRoute
  ModulesUsersMobileRoute: typeof ModulesUsersMobileRoute
  ModulesUsersWebRoute: typeof ModulesUsersWebRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/users-web': {
      id: '/modules/users-web'
      path: '/modules/users-web'
      fullPath: '/modules/users-web'
      preLoaderRoute: typeof ModulesUsersWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/users-mobile': {
      id: '/modules/users-mobile'
      path: '/modules/users-mobile'
      fullPath: '/modules/users-mobile'
      preLoaderRoute: typeof ModulesUsersMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/posts': {
      id: '/modules/posts'
      path: '/modules/posts'
      fullPath: '/modules/posts'
      preLoaderRoute: typeof ModulesPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ModulesPostsRoute: ModulesPostsRoute,
  ModulesUsersMobileRoute: ModulesUsersMobileRoute,
  ModulesUsersWebRoute: ModulesUsersWebRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
